name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to allow for proper merging

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Switch to generated branch
        run: |
          git checkout generated
          git pull origin generated

      - name: Merge main into generated
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git merge main -s ours

      - name: Run Gradle task
        run: |
          chmod +x ./gradlew
          ./gradlew runData

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update generated files from main branch"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated
